import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { useAuth } from '@/context/AuthContext';
import { SignupData, UserRole } from '@/types/auth';
import { Shield, Users, UserCheck, Settings, Eye, EyeOff } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { useTranslation } from '@/hooks/useTranslation';

interface SignupFormProps {
  onSwitchToLogin: () => void;
}

const getRoleOptions = (t: any): { value: UserRole; label: string; description: string; icon: React.ElementType }[] => [
  { value: 'tourist', label: t('roles.tourist'), description: t('roles.touristDesc'), icon: Users },
  { value: 'police', label: t('roles.police'), description: t('roles.policeDesc'), icon: Shield },
  { value: 'tourism', label: t('roles.tourism'), description: t('roles.tourismDesc'), icon: UserCheck },
  { value: 'admin', label: t('roles.admin'), description: t('roles.adminDesc'), icon: Settings },
];

const languages = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'as', name: 'অসমীয়া (Assamese)' },
  { code: 'bn', name: 'বাংলা (Bengali)' },
  { code: 'mni', name: 'মৈতৈলোন্ (Manipuri)' },
  { code: 'kha', name: 'Khasi' },
  { code: 'nsm', name: 'Nagamese' },
  { code: 'brx', name: 'बड़ो (Bodo)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'mr', name: 'मराठी (Marathi)' },
  { code: 'gu', name: 'ગુજરાતી (Gujarati)' },
];

const SignupForm: React.FC<SignupFormProps> = ({ onSwitchToLogin }) => {
  const { tSignup, tError, tCommon } = useTranslation();
  const [formData, setFormData] = useState<SignupData>({
    name: '',
    email: '',
    password: '',
    role: 'tourist',
    language: 'en',
    nationality: '',
  });
  const [touristDetails, setTouristDetails] = useState({
    confirmPassword: '',
    itinerary: '',
    emergencyContact: '',
    emergencyContactName: '',
    aadhaarNumber: '',
    passportNumber: '',
    expectedStayDuration: '',
    accommodationDetails: '',
  });
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const { signup, auth } = useAuth();
  const { toast } = useToast();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Validate password length
    if (formData.password.length < 6) {
      toast({
        variant: "destructive",
        title: 'Password Too Short',
        description: 'Password must be at least 6 characters long',
      });
      return;
    }
    
    // Validate passwords match for tourists
    if (formData.role === 'tourist' && formData.password !== touristDetails.confirmPassword) {
      toast({
        variant: "destructive",
        title: 'Password Mismatch',
        description: 'Passwords do not match',
      });
      return;
    }

    // Validate required fields for tourists
    if (formData.role === 'tourist') {
      if (!touristDetails.emergencyContact || !touristDetails.emergencyContactName) {
        toast({
          variant: "destructive",
          title: 'Required Field',
          description: 'Emergency contact is required for tourists',
        });
        return;
      }
    }
    
    // Only send required fields to the API
    const apiFormData = {
      name: formData.name,
      email: formData.email,
      password: formData.password,
      role: formData.role,
      language: formData.language,
      nationality: formData.nationality || undefined,
      walletAddress: undefined // Will be generated by backend if needed
    };
    
    const success = await signup(apiFormData);
    if (success) {
      toast({
        title: tSignup('success'),
        description: tSignup('welcome'),
      });
    } else {
      toast({
        variant: "destructive",
        title: 'Signup Failed',
        description: 'Please check your information and try again',
      });
    }
  };

  const roleOptions = getRoleOptions(tSignup);

  return (
    <Card className="w-full max-w-md shadow-elevated">
      <CardHeader className="text-center space-y-2">
        <div className="mx-auto w-12 h-12 rounded-full bg-gradient-brand flex items-center justify-center">
          <Shield className="w-6 h-6 text-white" />
        </div>
        <CardTitle className="text-2xl">{tSignup('title')}</CardTitle>
        <CardDescription>
          {tSignup('tagline')}
        </CardDescription>
      </CardHeader>
      
      <CardContent className="space-y-4">
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">{tSignup('name')}</Label>
            <Input
              id="name"
              placeholder={tSignup('namePlaceholder')}
              value={formData.name}
              onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
              required
            />
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="email">{tSignup('email')}</Label>
            <Input
              id="email"
              type="email"
              placeholder="your@email.com"
              value={formData.email}
              onChange={(e) => setFormData(prev => ({ ...prev, email: e.target.value }))}
              required
            />
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="password">{tSignup('password')}</Label>
            <div className="relative">
              <Input
                id="password"
                type={showPassword ? 'text' : 'password'}
                placeholder="••••••••"
                value={formData.password}
                onChange={(e) => setFormData(prev => ({ ...prev, password: e.target.value }))}
                required
                minLength={6}
              />
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="absolute right-2 top-1/2 -translate-y-1/2 h-auto p-1"
                onClick={() => setShowPassword(!showPassword)}
              >
                {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </Button>
            </div>
            <p className="text-xs text-muted-foreground">
              Password must be at least 6 characters long
            </p>
          </div>

          {formData.role === 'tourist' && (
            <div className="space-y-2">
              <Label htmlFor="confirmPassword">{tSignup('confirmPassword')}</Label>
              <div className="relative">
                <Input
                  id="confirmPassword"
                  type={showConfirmPassword ? 'text' : 'password'}
                  placeholder="••••••••"
                  value={touristDetails.confirmPassword}
                  onChange={(e) => setTouristDetails(prev => ({ ...prev, confirmPassword: e.target.value }))}
                  required
                />
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="absolute right-2 top-1/2 -translate-y-1/2 h-auto p-1"
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                >
                  {showConfirmPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </Button>
              </div>
            </div>
          )}
          
          <div className="space-y-2">
            <Label>{tSignup('role')}</Label>
            <Select value={formData.role} onValueChange={(role: UserRole) => setFormData(prev => ({ ...prev, role }))}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {roleOptions.map((role) => {
                  const Icon = role.icon;
                  return (
                    <SelectItem key={role.value} value={role.value}>
                      <div className="flex items-center gap-2">
                        <Icon className="w-4 h-4" />
                        <div>
                          <div className="font-medium">{role.label}</div>
                          <div className="text-xs text-muted-foreground">{role.description}</div>
                        </div>
                      </div>
                    </SelectItem>
                  );
                })}
              </SelectContent>
            </Select>
          </div>
          
          <div className="space-y-2">
            <Label>{tSignup('language')}</Label>
            <Select value={formData.language} onValueChange={(language) => setFormData(prev => ({ ...prev, language }))}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {languages.map((lang) => (
                  <SelectItem key={lang.code} value={lang.code}>
                    {lang.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          
          {formData.role === 'tourist' && (
            <>
              <div className="space-y-2">
                <Label htmlFor="nationality">{tSignup('nationality')}</Label>
                <Input
                  id="nationality"
                  placeholder={tSignup('nationalityPlaceholder')}
                  value={formData.nationality || ''}
                  onChange={(e) => setFormData(prev => ({ ...prev, nationality: e.target.value }))}
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="emergencyContactName">{tSignup('tourist.emergencyContactName')}</Label>
                <Input
                  id="emergencyContactName"
                  placeholder={tSignup('tourist.emergencyContactNamePlaceholder')}
                  value={touristDetails.emergencyContactName}
                  onChange={(e) => setTouristDetails(prev => ({ ...prev, emergencyContactName: e.target.value }))}
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="emergencyContact">{tSignup('tourist.emergencyContact')}</Label>
                <Input
                  id="emergencyContact"
                  placeholder={tSignup('tourist.emergencyContactPlaceholder')}
                  value={touristDetails.emergencyContact}
                  onChange={(e) => setTouristDetails(prev => ({ ...prev, emergencyContact: e.target.value }))}
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="aadhaarNumber">Aadhaar Number (Optional)</Label>
                <Input
                  id="aadhaarNumber"
                  placeholder="1234 5678 9012"
                  value={touristDetails.aadhaarNumber}
                  onChange={(e) => setTouristDetails(prev => ({ ...prev, aadhaarNumber: e.target.value }))}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="passportNumber">Passport Number (Optional)</Label>
                <Input
                  id="passportNumber"
                  placeholder="A1234567"
                  value={touristDetails.passportNumber}
                  onChange={(e) => setTouristDetails(prev => ({ ...prev, passportNumber: e.target.value }))}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="expectedStayDuration">Expected Stay Duration</Label>
                <Input
                  id="expectedStayDuration"
                  placeholder="e.g., 7 days, 2 weeks"
                  value={touristDetails.expectedStayDuration}
                  onChange={(e) => setTouristDetails(prev => ({ ...prev, expectedStayDuration: e.target.value }))}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="accommodationDetails">{tSignup('tourist.accommodationDetails')}</Label>
                <Input
                  id="accommodationDetails"
                  placeholder={tSignup('tourist.accommodationPlaceholder')}
                  value={touristDetails.accommodationDetails}
                  onChange={(e) => setTouristDetails(prev => ({ ...prev, accommodationDetails: e.target.value }))}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="itinerary">{tSignup('tourist.itinerary')}</Label>
                <Textarea
                  id="itinerary"
                  placeholder={tSignup('tourist.itineraryPlaceholder')}
                  value={touristDetails.itinerary}
                  onChange={(e) => setTouristDetails(prev => ({ ...prev, itinerary: e.target.value }))}
                  rows={3}
                />
              </div>
            </>
          )}
          
          <Button 
            type="submit" 
            className="w-full bg-gradient-brand hover:opacity-90" 
            disabled={auth.isLoading}
          >
            {auth.isLoading ? tSignup('creating') : tSignup('createAccount')}
          </Button>
        </form>
        
        <div className="text-center text-sm">
          <span className="text-muted-foreground">Already have an account? </span>
          <Button variant="link" className="p-0 h-auto" onClick={onSwitchToLogin}>
            {tSignup('haveAccount')}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};

export default SignupForm;